Repository VKCOM/gh-actions, pull requests merged in 2023-07, with the labels that each got.

#101 dependabot: use 'groups'; set schedule to weekly
  .github/dependabot.yml
Labels: dependencies

#95 Add close milestone workflows
  VKUI/close-milestone/.eslintrc.js
  VKUI/close-milestone/action.yml
  VKUI/close-milestone/jest.config.ts
  VKUI/close-milestone/package.json
  VKUI/close-milestone/src/main.ts
  VKUI/close-milestone/src/workflowHandler.ts
  VKUI/close-milestone/tsconfig.json
  VKUI/dispatch-publish-workflow/.eslintrc.js
  VKUI/dispatch-publish-workflow/action.yml
  VKUI/dispatch-publish-workflow/jest.config.ts
  VKUI/dispatch-publish-workflow/package.json
  VKUI/dispatch-publish-workflow/src/main.ts
  VKUI/dispatch-publish-workflow/tsconfig.json
  VKUI/find-actual-milestone/.eslintrc.js
  VKUI/find-actual-milestone/action.yml
  VKUI/find-actual-milestone/jest.config.ts
  VKUI/find-actual-milestone/package.json
  VKUI/find-actual-milestone/src/main.ts
  VKUI/find-actual-milestone/tsconfig.json
Labels: enhancement

#106 fix(@actions-internal/patch): optimize cherry-pick
  VKUI/patch/src/getMergeData.ts
  VKUI/patch/src/main.ts
  VKUI/patch/src/message.ts
Labels: bug

#107 fix(@actions-internal/patch): fetch with depth=2
  VKUI/patch/src/main.ts
Labels: bug
